export interface ExportOptions {
  title: string
  author?: string
  content: string
  format: 'pdf' | 'html' | 'docx' | 'epub' | 'md'
}

export async function exportDocument(options: ExportOptions): Promise<void> {
  const { title, content, format, author = 'lzeditor' } = options
  
  switch (format) {
    case 'html':
      exportHTML(title, content)
      break
    case 'md':
      exportMarkdown(title, content)
      break
    case 'pdf':
      await exportPDF(title, content)
      break
    case 'docx':
      exportDOCX(title, content, author)
      break
    case 'epub':
      await exportEPUB(title, content, author)
      break
  }
}

function exportHTML(title: string, content: string): void {
  const html = `<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title}</title>
  <style>
    body { font-family: sans-serif; line-height: 1.8; max-width: 800px; margin: 40px auto; padding: 20px; }
    h1, h2, h3 { color: #1a1a1a; }
    code { background: #f4f4f4; padding: 2px 6px; border-radius: 4px; }
    pre { background: #f4f4f4; padding: 16px; overflow-x: auto; border-radius: 8px; }
    blockquote { border-left: 4px solid #39FF9E; padding-left: 16px; margin: 16px 0; }
    table { border-collapse: collapse; width: 100%; margin: 16px 0; }
    th, td { border: 1px solid #ddd; padding: 8px 12px; }
    th { background: #f4f4f4; }
  </style>
</head>
<body>
  <h1>${title}</h1>
  ${content}
  <footer style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #eee; color: #999; font-size: 12px;">
    Generated by lzeditor
  </footer>
</body>
</html>`
  
  const blob = new Blob([html], { type: 'text/html' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `${title}.html`
  a.click()
  URL.revokeObjectURL(url)
}

function exportMarkdown(title: string, content: string): void {
  const md = `# ${title}

${content}

---
Generated by lzeditor
`
  const blob = new Blob([md], { type: 'text/markdown' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `${title}.md`
  a.click()
  URL.revokeObjectURL(url)
}

async function exportPDF(title: string, content: string): Promise<void> {
  const win = window.open('', '_blank')
  if (!win) return
  
  win.document.write(`
<!DOCTYPE html>
<html>
<head>
  <title>${title}</title>
  <style>
    @media print { body { margin: 0; padding: 20px; } }
    body { font-family: sans-serif; line-height: 1.8; max-width: 210mm; margin: 0 auto; padding: 20px; }
    h1, h2, h3 { page-break-after: avoid; }
  </style>
</head>
<body>
  <h1>${title}</h1>
  ${content}
</body>
</html>
  `)
  win.document.close()
  win.print()
}

function exportDOCX(title: string, content: string, author: string): void {
  const html = `
<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word">
<head>
  <meta charset="utf-8">
  <title>${title}</title>
  <style>
    body { font-family: serif; font-size: 12pt; }
    h1 { font-size: 24pt; }
    h2 { font-size: 18pt; }
  </style>
</head>
<body>
  <h1>${title}</h1>
  ${content}
</body>
</html>`
  
  const blob = new Blob(['\ufeff', html], { type: 'application/msword' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `${title}.doc`
  a.click()
  URL.revokeObjectURL(url)
}

async function exportEPUB(title: string, content: string, author: string): Promise<void> {
  const { generateEPUB } = await import('./epubGenerator')
  
  const chapters = [{ title: '正文', content }]
  const blob = await generateEPUB({ title, author, chapters })
  
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `${title}.epub`
  a.click()
  URL.revokeObjectURL(url)
}
